# Seção 2

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tensor = tf.constant([[23, 4], [32, 51]])

In [ ]:
tensor.numpy()

array([[23,  4],
       [32, 51]], dtype=int32)

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

arrays do numpy podem ser convertidos para tensores

In [ ]:
numpy_arr = np.array([[1, 2], [3, 4]])

In [ ]:
tensor_de_np = tf.constant(numpy_arr)
tensor_de_np

<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[1, 2],
       [3, 4]])>

In [ ]:
tf_var = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [ ]:
tf_var.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [ ]:
tf_var[0, 1].assign(10.)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 10.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>

## Operações

In [ ]:
tensor = tf.constant([[1, 2], [3, 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tensor * 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [ ]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
tensor_2 = tf.constant([[0, 1], [1, 0]])

In [ ]:
np.dot(tensor, tensor_2) # multiplicação de matrizes muito utilizada em RNs feitas a mao

array([[2, 1],
       [4, 3]], dtype=int32)

Strings

In [ ]:
tf_str = tf.constant('Victoria')

In [ ]:
tf_str

<tf.Tensor: shape=(), dtype=string, numpy=b'Victoria'>

In [ ]:
tf.strings.length(tf_str)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
tf.strings.unicode_decode(tf_str, 'UTF-8')

<tf.Tensor: shape=(8,), dtype=int32, numpy=array([ 86, 105,  99, 116, 111, 114, 105,  97], dtype=int32)>

In [ ]:
tf_str_arr = tf.constant(['TF', 'DL', 'ARR'])

In [ ]:
for string in tf_str_arr:
  print(string)

tf.Tensor(b'TF', shape=(), dtype=string)
tf.Tensor(b'DL', shape=(), dtype=string)
tf.Tensor(b'ARR', shape=(), dtype=string)


# Seção 3 - Construindo uma Rede Neural Artificial


In [ ]:
import numpy as np
import datetime
import tensorflow as tf
from tensorflow.keras.datasets import fashion_mnist

keras is a TensorFlow module nowadays.

In [ ]:
(x_train, y_train), (x_test, y_test) = fashion_mnist.load_data() # grey scale

In [ ]:
x_train[0] # huge 2D matrix with numbers representing an image

In [ ]:
y_train

array([9, 0, 0, ..., 3, 0, 5], dtype=uint8)

## Normalização
Serve para colocar o valor de cada pixel entre 0 e 1

Isso aumenta a performance da rede neural

In [ ]:
x_train = x_train / 255

In [ ]:
x_test = x_test / 255

In [ ]:
x_train[0]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.    

## Reshaping

Reshaping matrixes is an important step cuz we're working with dense rns, so they need vectors as inputs. 

In [ ]:
x_train.shape # 60000 images. each one has 28x28 pixels

(60000, 28, 28)

In [ ]:
x_train = x_train.reshape(-1, 28*28)

In [ ]:
x_train.shape

(60000, 784)

In [ ]:
x_train[0]

In [ ]:
x_test = x_test.reshape(-1, 28*28)

In [ ]:
x_test[0]

## Construindo a rede

In [ ]:
model = tf.keras.models.Sequential() # sequential type defines a set of layers

In [ ]:
model

### Adding the first fully-connected layer

In [ ]:
# primeira camada oculta, input_shpe is equals to (784, ) because of the image shape
model.add(tf.keras.layers.Dense(units=128, activation='relu', input_shape=(784, )))

### Dropout layer

this layer will try to avoid overfitting

In [ ]:
model.add(tf.keras.layers.Dropout(0.2)) # it means will drop 20% of the neuros

In [ ]:
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))
model.add(tf.keras.layers.Dense(units=128, activation='relu'))
model.add(tf.keras.layers.Dropout(0.2))

### Output layer

In [ ]:
model.add(tf.keras.layers.Dense(units=10, activation='softmax')) 
# it's ten cuz we have 10 labels and the activation = softm. cuz it's a multilabel classification
# if we had 2 labels, activation would be sigmoid

### Compiling

In [ ]:
# sparse categorical entropy is better when we are not using hot encoder and dummy variables
model.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['sparse_categorical_accuracy'])

In [ ]:
model.summary()

Model: "sequential_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_23 (Dense)            (None, 128)               100480    
                                                                 
 dropout_11 (Dropout)        (None, 128)               0         
                                                                 
 dense_24 (Dense)            (None, 128)               16512     
                                                                 
 dropout_12 (Dropout)        (None, 128)               0         
                                                                 
 dense_25 (Dense)            (None, 128)               16512     
                                                                 
 dropout_13 (Dropout)        (None, 128)               0         
                                                                 
 dense_26 (Dense)            (None, 10)              

### Training

In [ ]:
model.fit(x_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 1.0082 - sparse_categorical_accuracy: 0.6330
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.6251 - sparse_categorical_accuracy: 0.7781
Epoch 3/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5359 - sparse_categorical_accuracy: 0.8122
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4907 - sparse_categorical_accuracy: 0.8250
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4623 - sparse_categorical_accuracy: 0.8365
Epoch 6/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4421 - sparse_categorical_accuracy: 0.8429
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4257 - sparse_categorical_accuracy: 0.8478
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4114 - sparse_categorical_accuracy: 0.8538
Epoch 9/10
1875/1875 [==========

### Evaluantion

In [ ]:
test_loss, test_accuracy = model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.3756 - sparse_categorical_accuracy: 0.8619


In [ ]:
print(f'test accuracy: {test_accuracy}')

test accuracy: 0.8618999719619751


In [ ]:
test_loss

0.3216933012008667